version: "3.9"

services:
  template_env:
    container_name: template_env
    build:
      context: "./template"
      dockerfile: "Dockerfile"
      target: "packaged"
      args  :
        USERNAME: ${USERNAME:-user}
        USERPASS: ${USERPASS:-1234}
        ROOTPASS: ${ROOTPASS:-1234}
        PACKAGES: ${PACKAGES:-}
        GIT_EMAIL: ${GIT_EMAIL:-}
        GIT_NAME: ${GIT_NAME:-}
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=${DISPLAY}
      - TERM=xterm
    security_opt:
      - seccomp:unconfined #for chrome
    # network_mode: "host"
    networks:
      net_00:
        ipv4_address: "11.100.101.111"
    hostname: "template"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  net_00:
    name: net_00
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: net_00
    ipam:
      driver: default
      config:
        - subnet: 11.0.0.0/8
          ip_range: 11.0.0.0/8
          gateway: 11.100.101.110
